Repository swyp-7/stamp-Backend, pull requests merged in 2025-02, with the labels that each got.

#2 feat(common-1): 공통 응답 형식 정의 및 기본 예외 정의
  build.gradle
  src/main/java/com/stamp/api/controller/HealthCheckController.java
  src/main/java/com/stamp/global/exception/Error.java
  src/main/java/com/stamp/global/exception/GlobalErrorCode.java
  src/main/java/com/stamp/global/exception/GlobalExceptionHandler.java
  src/main/java/com/stamp/global/response/ApplicationResponse.java
  src/test/java/com/stamp/global/ResponseControllerTest.java
Labels: enhancement

#6 [#5] Github Actions' workflow 생성
  .github/ISSUE_TEMPLATE/bug-issue.md
  .github/ISSUE_TEMPLATE/feature-issue.md
  .github/ISSUE_TEMPLATE/refactoring-issue.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build & deploy.yml
  appspec.yml
Labels: enhancement

#11 [#3] 기본 로그인 및 소셜 로그인 구현
  build.gradle
  src/main/java/com/stamp/StampApplication.java
  src/main/java/com/stamp/api/auth/controller/AuthController.java
  src/main/java/com/stamp/api/auth/dto/request/LoginReq.java
  src/main/java/com/stamp/api/auth/dto/request/SocialLoginReq.java
  src/main/java/com/stamp/api/auth/dto/response/LoginRes.java
  src/main/java/com/stamp/api/auth/entity/OAuthId.java
  src/main/java/com/stamp/api/auth/exception/AuthErrorCode.java
  src/main/java/com/stamp/api/auth/infra/oauth/OAuthMemberClient.java
  src/main/java/com/stamp/api/auth/infra/oauth/OAuthMemberClientComposite.java
  src/main/java/com/stamp/api/auth/infra/oauth/OAuthRequestProvider.java
  src/main/java/com/stamp/api/auth/infra/oauth/OAuthRequestProviderComposite.java
  src/main/java/com/stamp/api/auth/infra/oauth/OAuthUserDetails.java
  src/main/java/com/stamp/api/auth/infra/oauth/ProviderType.java
  src/main/java/com/stamp/api/auth/infra/oauth/ProviderTypeConverter.java
  src/main/java/com/stamp/api/auth/infra/oauth/kakao/KakaoApiClient.java
  src/main/java/com/stamp/api/auth/infra/oauth/kakao/KakaoMemberClient.java
  src/main/java/com/stamp/api/auth/infra/oauth/kakao/KakaoOAuthRequestProvider.java
  src/main/java/com/stamp/api/auth/infra/oauth/kakao/dto/KakaoMemberResponse.java
  src/main/java/com/stamp/api/auth/infra/oauth/kakao/dto/KakaoToken.java
  src/main/java/com/stamp/api/auth/service/AuthService.java
  src/main/java/com/stamp/api/auth/service/AuthServiceImpl.java
  src/main/java/com/stamp/api/auth/service/OAuthService.java
  src/main/java/com/stamp/api/auth/service/OAuthServiceImpl.java
  src/main/java/com/stamp/api/controller/HealthCheckController.java
  src/main/java/com/stamp/api/employeruser/dto/CreateEmployerUserReq.java
  src/main/java/com/stamp/api/employeruser/entity/EmployerUser.java
  src/main/java/com/stamp/api/employeruser/repository/EmployerUserRepository.java
  src/main/java/com/stamp/api/signup/controller/SignUpController.java
  src/main/java/com/stamp/api/signup/dto/request/SignUpReq.java
  src/main/java/com/stamp/api/signup/service/SignUpService.java
  src/main/java/com/stamp/api/signup/service/SignUpServiceImpl.java
  src/main/java/com/stamp/api/store/dto/request/CreateStoreReq.java
  src/main/java/com/stamp/api/store/entity/Store.java
  src/main/java/com/stamp/api/store/exception/StoreErrorCode.java
  src/main/java/com/stamp/api/store/repository/StoreRepository.java
  src/main/java/com/stamp/api/store/service/StoreService.java
  src/main/java/com/stamp/api/store/service/StoreServiceImpl.java
  src/main/java/com/stamp/global/config/EncryptConfig.java
  src/main/java/com/stamp/global/config/HttpInterfaceConfig.java
  src/main/java/com/stamp/global/config/WebMvcConfig.java
  src/main/java/com/stamp/global/config/oauth/kakao/KakaoOAuthConfig.java
  src/main/java/com/stamp/global/config/security/JasyptConfig.java
  src/main/java/com/stamp/global/config/security/WebSecurityConfig.java
  src/main/java/com/stamp/global/config/security/filter/JwtAuthentication.java
  src/main/java/com/stamp/global/config/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/stamp/global/exception/DomainException.java
  src/main/java/com/stamp/global/exception/Error.java
  src/main/java/com/stamp/global/exception/GlobalErrorCode.java
  src/main/java/com/stamp/global/exception/GlobalExceptionHandler.java
  src/main/java/com/stamp/global/jwt/JwtResponse.java
  src/main/java/com/stamp/global/jwt/util/JwtTokenProvider.java
  src/main/java/com/stamp/global/response/ApplicationResponse.java
  src/main/resources/application.yml
  src/test/java/com/stamp/StampApplicationTests.java
  src/test/java/com/stamp/global/ResponseControllerTest.java
Labels: enhancement

#14 [13] application.yml 파일 구조 수정
  .gitignore
  src/main/resources/application.yml
  src/main/resources/yml/db/application-dev.yml
  src/main/resources/yml/db/application-local.yml
  src/main/resources/yml/global/application-global.yml
  src/main/resources/yml/logging/application-basic.yml
  src/main/resources/yml/logging/application-custom.yml
  src/main/resources/yml/logging/application-detailed.yml
  src/main/resources/yml/logging/application-persist.yml
Labels: refactor

#16 [#12] CI/CD에 jasypt 관련 설정 반영
  scripts/start.sh
Labels: bug

#19 [#15] 개발 DB 구축
  src/main/resources/application.yml
  src/main/resources/yml/db/application-dev.yml
Labels: enhancement

#22 [#12] CI/CD 파이프라인 수정
  .github/workflows/build & deploy.yml
  .gitignore
  scripts/start.sh
  scripts/stop.sh
Labels: bug

#21 [#18]최초 소셜 로그인 사용자 등록 여정 추가 개발 및 dto등 골자 리팩토링
  src/main/java/com/stamp/api/auth/controller/AuthController.java
  src/main/java/com/stamp/api/auth/dto/request/LoginEmployerReq.java
  src/main/java/com/stamp/api/auth/dto/request/LoginReq.java
  src/main/java/com/stamp/api/auth/dto/request/SocialLoginEmployerReq.java
  src/main/java/com/stamp/api/auth/dto/request/SocialLoginReq.java
  src/main/java/com/stamp/api/auth/dto/response/LoginRes.java
  src/main/java/com/stamp/api/auth/exception/AuthErrorCode.java
  src/main/java/com/stamp/api/auth/infra/oauth/OAuthMemberClient.java
  src/main/java/com/stamp/api/auth/infra/oauth/OAuthMemberClientComposite.java
  src/main/java/com/stamp/api/auth/infra/oauth/kakao/KakaoMemberClient.java
  src/main/java/com/stamp/api/auth/service/AuthService.java
  src/main/java/com/stamp/api/auth/service/AuthServiceImpl.java
  src/main/java/com/stamp/api/auth/service/OAuthService.java
  src/main/java/com/stamp/api/auth/service/OAuthServiceImpl.java
  src/main/java/com/stamp/api/employeruser/dto/CreateSocialEmployerUserReq.java
  src/main/java/com/stamp/api/employeruser/entity/EmployerUser.java
  src/main/java/com/stamp/api/employeruser/service/CreateEmployerUserService.java
  src/main/java/com/stamp/api/employeruser/service/CreateEmployerUserServiceImpl.java
  src/main/java/com/stamp/api/signup/employer/controller/SignUpEmployerController.java
  src/main/java/com/stamp/api/signup/employer/dto/request/SignUpEmployerReq.java
  src/main/java/com/stamp/api/signup/employer/service/SignUpEmployerService.java
  src/main/java/com/stamp/api/signup/employer/service/SignUpEmployerServiceImpl.java
  src/main/java/com/stamp/api/signup/service/SignUpService.java
  src/main/java/com/stamp/api/signup/service/SignUpServiceImpl.java
  src/main/java/com/stamp/api/store/entity/Store.java
  src/main/java/com/stamp/api/store/service/CreateStoreService.java
  src/main/java/com/stamp/api/store/service/CreateStoreServiceImpl.java
  src/main/java/com/stamp/global/exception/GlobalErrorCode.java
  src/main/resources/yml/db/application-local.yml
  src/main/resources/yml/global/application-global.yml
  src/main/resources/yml/logging/application-custom.yml
Labels: enhancement, refactor

#31 [#30] .gitignore 수정으로 인해 삭제된 .yml 파일 복구
  .gitignore
  src/main/resources/yml/db/application-local.yml
  src/main/resources/yml/logging/application-custom.yml
Labels: bug

#34 [#32] 직원 수정 api 개발 및 도메인 리팩토링
  src/main/java/com/stamp/api/employee/controller/EmployeeController.java
  src/main/java/com/stamp/api/employee/dto/request/UpdateEmployeeReq.java
  src/main/java/com/stamp/api/employee/dto/response/ReadEmployeeRes.java
  src/main/java/com/stamp/api/employee/entity/Employee.java
  src/main/java/com/stamp/api/employee/exception/EmployeeErrorCode.java
  src/main/java/com/stamp/api/employee/service/UpdateEmployeeService.java
  src/main/java/com/stamp/api/employee/service/UpdateEmployeeServiceImpl.java
  src/main/java/com/stamp/api/employeeschedule/dto/request/UpdateEmployeeScheduleReq.java
  src/main/java/com/stamp/api/employeeschedule/dto/response/ReadEmployeeScheduleRes.java
  src/main/java/com/stamp/api/employeeschedule/entity/EmployeeSchedule.java
  src/main/java/com/stamp/api/signup/employer/dto/request/SignUpEmployerReq.java
  src/main/java/com/stamp/api/store/controller/StoreController.java
  src/main/java/com/stamp/api/store/dto/response/ReadStoreRes.java
  src/main/java/com/stamp/api/store/entity/Store.java
  src/main/java/com/stamp/api/store/service/CreateStoreServiceImpl.java
  src/main/java/com/stamp/api/store/service/ReadStoreServiceImpl.java
  src/main/java/com/stamp/api/store/service/UpdateStoreService.java
  src/main/java/com/stamp/api/store/service/UpdateStoreServiceImpl.java
  src/main/java/com/stamp/api/storeschedule/dto/response/ReadStoreScheduleRes.java
  src/main/java/com/stamp/api/storeschedule/entity/StoreSchedule.java
  src/main/java/com/stamp/global/config/security/WebSecurityConfig.java
Labels: enhancement

#43 [#42] 직원 스케줄 삭제 api 개발
  src/main/java/com/stamp/api/employee/controller/EmployeeController.java
  src/main/java/com/stamp/api/employee/entity/Employee.java
  src/main/java/com/stamp/api/employee/service/DeleteEmployeeService.java
  src/main/java/com/stamp/api/employee/service/DeleteEmployeeServiceImpl.java
  src/main/java/com/stamp/api/employeeschedule/entity/EmployeeSchedule.java
  src/main/java/com/stamp/api/store/service/CreateStoreServiceImpl.java
Labels: enhancement

#48 [#47] 가게 정보 수정 골자 변경
  src/main/java/com/stamp/api/employeruser/entity/EmployerUser.java
  src/main/java/com/stamp/api/store/dto/request/UpdateStoreReq.java
  src/main/java/com/stamp/api/store/service/UpdateStoreServiceImpl.java
Labels: enhancement

#54 hotfix: jwt 토큰 클레임시 오타 수정
  src/main/java/com/stamp/global/config/security/filter/JwtAuthenticationFilter.java
Labels: bug

#56 [#55] QR을 이용한 직원 출/퇴근 로직 구현
  build.gradle
  src/main/java/com/stamp/api/attendance/controller/AttendanceController.java
  src/main/java/com/stamp/api/attendance/controller/AttendanceControllerLocal.java
  src/main/java/com/stamp/api/attendance/dto/requeset/AttendanceReq.java
  src/main/java/com/stamp/api/attendance/dto/response/QRCodeRes.java
  src/main/java/com/stamp/api/attendance/entity/Attendance.java
  src/main/java/com/stamp/api/attendance/entity/AttendanceEnum.java
  src/main/java/com/stamp/api/attendance/entity/QRAuthCode.java
  src/main/java/com/stamp/api/attendance/exception/AttendanceErrorCode.java
  src/main/java/com/stamp/api/attendance/exception/QRCodeErrorCode.java
  src/main/java/com/stamp/api/attendance/repository/AttendanceRepository.java
  src/main/java/com/stamp/api/attendance/repository/QRAuthCodeRepository.java
  src/main/java/com/stamp/api/attendance/service/AttendanceService.java
  src/main/java/com/stamp/api/attendance/service/AttendanceServiceImpl.java
  src/main/java/com/stamp/api/attendance/service/LocalAttendanceService.java
  src/main/java/com/stamp/api/attendance/service/LocalAttendanceServiceImpl.java
  src/main/java/com/stamp/api/attendance/service/LocalQRManageService.java
  src/main/java/com/stamp/api/attendance/service/LocalQRManageServiceImpl.java
  src/main/java/com/stamp/api/attendance/service/QRManageService.java
  src/main/java/com/stamp/api/attendance/service/QRManageServiceImpl.java
  src/main/java/com/stamp/global/exception/GlobalExceptionHandler.java
  src/test/java/com/stamp/api/attendance/service/AttendanceServiceImplUnitTest.java
  src/test/java/com/stamp/api/attendance/service/QRManageServiceImplUnitTest.java
Labels: enhancement

#59 [#55] 프론트 로컬 테스트용 QR코드 생성로직 수정
  src/main/java/com/stamp/api/attendance/service/LocalQRManageServiceImpl.java
Labels: refactor

#62 [#61] 직원 로그인 반환값 수정
  src/main/java/com/stamp/api/auth/employer/controller/AuthEmployerController.java
  src/main/java/com/stamp/api/auth/employer/dto/response/EmployeeLoginRes.java
  src/main/java/com/stamp/api/auth/employer/service/AuthEmployeeService.java
  src/main/java/com/stamp/api/auth/employer/service/AuthEmployeeServiceImpl.java
Labels: front
