Repository swyp-7/stamp-Backend, pull requests merged in 2025-03, with the labels that each got.

#66 [#65] 직원 로그인 반환값 수정
  src/main/java/com/stamp/api/auth/employer/dto/response/EmployeeLoginRes.java
  src/main/java/com/stamp/api/auth/employer/service/AuthEmployeeServiceImpl.java
Labels: front

#68 [#67] QR코드 조회 로직 변경
  src/main/java/com/stamp/api/attendance/service/LocalQRManageServiceImpl.java
  src/main/java/com/stamp/api/attendance/service/QRManageServiceImpl.java
  src/test/java/com/stamp/api/attendance/service/QRManageServiceImplUnitTest.java
Labels: front

#69 [#55] 직원 출/퇴근 기록 조회 API 구현
  src/main/java/com/stamp/api/attendance/controller/AttendanceController.java
  src/main/java/com/stamp/api/attendance/dto/response/AttendanceRes.java
  src/main/java/com/stamp/api/attendance/repository/AttendanceRepository.java
  src/main/java/com/stamp/api/attendance/service/AttendanceService.java
  src/main/java/com/stamp/api/attendance/service/AttendanceServiceImpl.java
  src/test/java/com/stamp/api/attendance/service/AttendanceQueryServiceImplUnitTest.java
Labels: enhancement

#71 [#70] 출퇴근 기록 조회 API 엔드포인트 수정
  src/main/java/com/stamp/api/attendance/controller/AttendanceController.java
Labels: bug

#72 [#70] 출/퇴근 기록 조회 API의 End point 수정
  src/main/java/com/stamp/api/attendance/controller/AttendanceController.java
Labels: bug

#73 [#55] 가게의 직원 출/퇴근 기록 수정 API 구현
  src/main/java/com/stamp/api/attendance/controller/AttendanceController.java
  src/main/java/com/stamp/api/attendance/controller/AttendanceControllerLocal.java
  src/main/java/com/stamp/api/attendance/dto/requeset/AttendanceUpdateReq.java
  src/main/java/com/stamp/api/attendance/dto/response/AttendanceRes.java
  src/main/java/com/stamp/api/attendance/entity/Attendance.java
  src/main/java/com/stamp/api/attendance/entity/AttendanceEnum.java
  src/main/java/com/stamp/api/attendance/exception/AttendanceErrorCode.java
  src/main/java/com/stamp/api/attendance/service/AttendanceService.java
  src/main/java/com/stamp/api/attendance/service/AttendanceServiceImpl.java
  src/main/java/com/stamp/api/attendance/service/frontlocal/LocalAttendanceService.java
  src/main/java/com/stamp/api/attendance/service/frontlocal/LocalAttendanceServiceImpl.java
  src/main/java/com/stamp/api/attendance/service/frontlocal/LocalQRManageService.java
  src/main/java/com/stamp/api/attendance/service/frontlocal/LocalQRManageServiceImpl.java
  src/test/java/com/stamp/api/attendance/service/AttendanceQueryServiceImplUnitTest.java
  src/test/java/com/stamp/api/attendance/service/AttendanceServiceImplQrUnitTest.java
  src/test/java/com/stamp/api/attendance/service/AttendanceServiceImplQueryUnitTest.java
Labels: enhancement

#76 [#55] 직원용 출퇴근 기록 조회 API 구현
  src/main/java/com/stamp/api/attendance/repository/AttendanceRepository.java
  src/main/java/com/stamp/api/attendance/service/AttendanceService.java
  src/main/java/com/stamp/api/attendance/service/AttendanceServiceImpl.java
  src/main/java/com/stamp/api/attendance/service/QRManageService.java
  src/main/java/com/stamp/api/employee/controller/EmployeeController.java
  src/main/java/com/stamp/api/employee/controller/StoreEmployeeController.java
  src/main/java/com/stamp/api/employee/dto/response/EmployeeAttendacneRes.java
  src/main/java/com/stamp/api/employee/exception/EmployeeErrorCode.java
  src/main/java/com/stamp/api/employee/service/EmployeeAttendanceService.java
  src/main/java/com/stamp/api/employee/service/EmployeeAttendanceServiceImpl.java
  src/main/java/com/stamp/api/employee/service/EmployeeAuthorizationService.java
  src/main/java/com/stamp/api/employee/service/EmployeeAuthorizationServiceImpl.java
  src/main/java/com/stamp/api/employee/service/EmployeeService.java
  src/main/java/com/stamp/api/employee/service/EmployeeServiceImpl.java
  src/main/java/com/stamp/api/employee/service/ReadEmployeeServiceImpl.java
  src/main/java/com/stamp/api/employee/service/UpdateEmployeeServiceImpl.java
  src/test/java/com/stamp/api/attendance/service/AttendanceServiceImplQueryUnitTest.java
  src/test/java/com/stamp/api/employee/service/EmployeeAttendanceServiceTest.java
Labels: enhancement

#78 [#77] 추가 근무 요청 생성, 조회, 수락 및 거절 기능 구현
  src/main/java/com/stamp/api/employeeschedule/repository/EmployeeScheduleRepository.java
  src/main/java/com/stamp/api/extraShift/controller/ExtraShiftController.java
  src/main/java/com/stamp/api/extraShift/dto/request/ExtraShiftReq.java
  src/main/java/com/stamp/api/extraShift/dto/response/ExtraShiftRes.java
  src/main/java/com/stamp/api/extraShift/entity/ExtraShift.java
  src/main/java/com/stamp/api/extraShift/exception/ExtraShiftErrorCode.java
  src/main/java/com/stamp/api/extraShift/repository/ExtraShiftRepository.java
  src/main/java/com/stamp/api/extraShift/service/ExtraShiftService.java
  src/main/java/com/stamp/api/extraShift/service/ExtraShiftServiceImpl.java
Labels: enhancement

#81 [#79]
  scripts/start.sh
  scripts/stop.sh
  src/main/java/com/stamp/global/config/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/stamp/global/exception/GlobalExceptionHandler.java
Labels: enhancement

#84 [#80] 직원 급여 관리 도메인 구현
  src/main/java/com/stamp/api/attendance/service/AttendanceService.java
  src/main/java/com/stamp/api/attendance/service/AttendanceServiceImpl.java
  src/main/java/com/stamp/api/employee/entity/IsPaid.java
  src/main/java/com/stamp/api/employee/repository/IsPaidRepository.java
  src/main/java/com/stamp/api/store/controller/StoreController.java
  src/main/java/com/stamp/api/store/dto/request/WageStatusReq.java
  src/main/java/com/stamp/api/store/dto/response/WageRes.java
  src/main/java/com/stamp/api/store/service/WageService.java
  src/main/java/com/stamp/api/store/service/WageServiceImpl.java
Labels: enhancement

#91 [#90] 추가 근무 상태 추가 및 필터링 조회 기능 추가
  src/main/java/com/stamp/api/extraShift/controller/ExtraShiftController.java
  src/main/java/com/stamp/api/extraShift/entity/ExtraShift.java
  src/main/java/com/stamp/api/extraShift/entity/RequestStatus.java
  src/main/java/com/stamp/api/extraShift/repository/ExtraShiftRepository.java
  src/main/java/com/stamp/api/extraShift/service/ReadExtraShiftService.java
  src/main/java/com/stamp/api/extraShift/service/ReadExtraShiftServiceImpl.java
Labels: enhancement

#95 [#93] 직원 출퇴근 기록 수정 API 수정
  src/main/java/com/stamp/api/attendance/controller/AttendanceController.java
  src/main/java/com/stamp/api/attendance/dto/requeset/AttendanceMultiUpdateReq.java
  src/main/java/com/stamp/api/attendance/service/AttendanceService.java
  src/main/java/com/stamp/api/attendance/service/AttendanceServiceImpl.java
Labels: front
